spring:
  application:
    name: proxy-bff

proxy.rules:
  - prefix: /api/test
    target: http://localhost:8080/test

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /swagger/openapi.yaml
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config

logging:
  level:
    test: DEBUG